# Generated by Django 5.0.6 on 2024-06-26 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_grade_screenshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='cycle',
            field=models.CharField(choices=[('DAW', 'DAW'), ('DAM', 'DAM')], default='DAW', max_length=3),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='module',
            field=models.CharField(choices=[('DAM-M06', 'DAM-M06. Accés a dades'), ('DAM-M07', 'DAM-M07. Desenvolupament d’interfícies'), ('DAM-M08', 'DAM-M08. Progr. multimèdia i dispositius mòbils'), ('DAM-M09', 'DAM-M09. Programació de serveis i processos'), ('DAM-M10', 'DAM-M10. Sistemes de Gestió Empresarial'), ('DAM-M13', 'DAM-M13. Projecte'), ('DAW-M06', 'DAW-M06. Desenvolupament web en entorn client'), ('DAW-M07', "DAW-M07. Desenvolupament web d'entorn servidor"), ('DAW-M08', 'DAW-M08. Desplegament d’aplicacions web'), ('DAW-M09', 'DAW-M09. Disseny d’interfícies web'), ('DAW-M12', 'DAW-M12. Projecte')], max_length=50),
        ),
    ]
